services:

  nginx:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway

  gateway:
    build: ./gateway
    container_name: my-gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    volumes:
      - ./gateway:/app
      - ./proto:/proto
    depends_on:
      - ping

  ping:
    build: ./services/ping
    container_name: ping-ms
    ports:
      - "${PING_GRPC_PORT}:${PING_GRPC_PORT}"
    volumes:
      - ./services/ping:/app-ping
      - ./proto:/proto

  monitoring:
    build: ./services/monitoring
    container_name: monitoring-MS
    ports:
      - "${MONITORING_GRPC_PORT}:${MONITORING_GRPC_PORT}"
    environment:
      MONGO_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_URL: ${MONGO_URL}
    volumes:
      - ./services/monitoring:/app-monitoring
      - ./proto:/proto
    depends_on:
      - mongo-monitoring

  mongo-monitoring:
    image: mongo:latest
    container_name: mongo-monitoring
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - upy-monitoringMS-db:/data/db

volumes:
  upy-monitoringMS-db: